### ISSUE TITLE
use github actions to use GH issues in order to submit talk ideas

### ISSUE THREAD

**Issue by tormath1** [sre-paris/meetups#12]
Just for the record; we should use the same mechanism as this repo: https://github.com/sre-paris/reliability.re in order to ease talk proposals for meetups CFP. 

This action needs to be copied: https://github.com/sre-paris/reliability.re/blob/main/.github/workflows/content.yml

and this script too https://github.com/sre-paris/reliability.re/tree/main/scripts/create-content. Of course with some modifications to fit the usecase.

What should be the workflow ? 

1. User open an issue template
2. The issue holds the label "talk proposal"
3. How should we deal with the meetup "id" ? (currently number 9)

**Comment by pabluk** [comment]
Thanks for opening this issue, it could help to discuss about the implementation because I was thinking about it.

Totally agree on points 1. and 2., and I asked me the same question regarding 3.

Maybe we could deal with the meetup "id" manually, I mean, we could automatically move all the validated proposal to a single directory, kind of pool of proposals, and when we are ready for a next meetup and after confirmation from the speaker we can manually move them to the right ID directory, because in any case this last step is always manual. What do you think about it?

**Comment by tormath1** [comment]
@pabluk pool of "proposals" looks good to me in a first implementation. :) 

So we should have something like this:
1. User open an issue template
2. The issue holds the label "talk proposal"
3. Python script will copy the issue content into a file named after the title of the issue and located into "talks" pool folder
4. PR will be open
5. PR will be reviewed / approved
6. Issue will be closed


For the issue template, should we keep the current format (https://github.com/sre-paris/meetups/blob/master/cfp/template.md) ?

**Comment by pabluk** [comment]
> So we should have something like this:
> 
>     1. User open an issue template
> 
>     2. The issue holds the label "talk proposal"
> 
>     3. Python script will copy the issue content into a file named after the title of the issue and located into "talks" pool folder
> 
>     4. PR will be open
> 
>     5. PR will be reviewed / approved
> 
>     6. Issue will be closed
> 
Yes :+1: that could allow to re-use easily the same action/script from Reliability.re.
 
> For the issue template, should we keep the current format (https://github.com/sre-paris/meetups/blob/master/cfp/template.md) ?

Yep, all the fields in that template seems good to me. Maybe we could put the abstract field at the end in the same way that was done in reliability.re https://raw.githubusercontent.com/sre-paris/reliability.re/main/.github/ISSUE_TEMPLATE/new-content.md
